#  Import necessary libraries

In [14]:
import pandas as pd

#  Load the dataset

In [15]:
file_path = 'Online retail.xlsx'
df = pd.read_excel(file_path)

#  Show first few rows to understand the data

In [16]:
df.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [18]:
# Split each row into a list of items
transactions = df.iloc[:, 0].apply(lambda x: x.split(','))

# Convert to list of lists
transactions_list = transactions.tolist()

# Get a list of all unique items
all_items = set(item.strip() for sublist in transactions_list for item in sublist)

# ðŸ”§ Convert set to list
all_items = list(all_items)

# Create a DataFrame with one column per item
encoded_df = pd.DataFrame(0, index=range(len(transactions_list)), columns=all_items)

# Fill with 1 where item is present
for i, items in enumerate(transactions_list):
    for item in items:
        encoded_df.at[i, item.strip()] = 1

# Show first few rows
encoded_df.head()

,tomato sauce,fromage blanc,extra dark chocolate,mayonnaise,carrots,salmon,eggs,ham,pet food,pancakes,...,corn,red wine,muffins,whole wheat rice,white wine,meatballs,shrimp,frozen smoothie,cooking oil,mashed potato
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.15.2)
Requirement already satisfied: numpy>=1.16.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (2.2.5)
Requirement already satisfied: pandas>=0.24.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (3.10.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------------------------------- -------- 1.0/1.4 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 4.5 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4
Note: you may need to restart the kernel to use updated packages.

In [21]:
from mlxtend.frequent_patterns import apriori, association_rules

# ðŸ”Ž Find frequent itemsets with min_support threshold
frequent_itemsets = apriori(encoded_df, min_support=0.02, use_colnames=True)

# ðŸ’¬ Generate the rules from frequent itemsets
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Show the rules
rules.head()

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(eggs),(pancakes),0.179733,0.095067,0.021733,0.120920,1.271948,1.0,0.004647,1.029409,0.260652,0.085880,0.028569,0.174766
1,(pancakes),(eggs),0.095067,0.179733,0.021733,0.228612,1.271948,1.0,0.004647,1.063364,0.236265,0.085880,0.059588,0.174766
2,(eggs),(mineral water),0.179733,0.238267,0.050933,0.283383,1.189351,1.0,0.008109,1.062957,0.194090,0.138758,0.059228,0.248574
3,(mineral water),(eggs),0.238267,0.179733,0.050933,0.213766,1.189351,1.0,0.008109,1.043286,0.209004,0.138758,0.041490,0.248574
4,(eggs),(milk),0.179733,0.129600,0.030800,0.171365,1.322261,1.0,0.007507,1.050402,0.297122,0.110579,0.047984,0.204510